/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Attachment } from '../models/attachment';
import { OrderLine } from '../models/order-line';
export interface Order {
  attachments?: Array<Attachment>;
  dateOrder: string;
  id?: number;
  orderLines?: Array<OrderLine>;
  status?: string;
}
