/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Attachment } from '../../models/attachment';

export interface CreateAttachment$Params {
  orderId: number;
      body: Attachment
}

export function createAttachment(http: HttpClient, rootUrl: string, params: CreateAttachment$Params, context?: HttpContext): Observable<StrictHttpResponse<Attachment>> {
  const rb = new RequestBuilder(rootUrl, createAttachment.PATH, 'post');
  if (params) {
    rb.path('orderId', params.orderId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Attachment>;
    })
  );
}

createAttachment.PATH = '/api/orders/{orderId}/attachemets';
