/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { Attachment } from '../models/attachment';
import { createAttachment } from '../fn/attachments/create-attachment';
import { CreateAttachment$Params } from '../fn/attachments/create-attachment';
import { deleteAttachment } from '../fn/attachments/delete-attachment';
import { DeleteAttachment$Params } from '../fn/attachments/delete-attachment';
import { getAllAttachments } from '../fn/attachments/get-all-attachments';
import { GetAllAttachments$Params } from '../fn/attachments/get-all-attachments';
import { getAttachmentById } from '../fn/attachments/get-attachment-by-id';
import { GetAttachmentById$Params } from '../fn/attachments/get-attachment-by-id';

@Injectable({ providedIn: 'root' })
export class AttachmentsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getAllAttachments()` */
  static readonly GetAllAttachmentsPath = '/api/orders/{orderId}/attachemets';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllAttachments()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllAttachments$Response(params: GetAllAttachments$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<Attachment>>> {
    const obs = getAllAttachments(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllAttachments$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllAttachments(params: GetAllAttachments$Params, context?: HttpContext): Promise<Array<Attachment>> {
    const resp = this.getAllAttachments$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<Attachment>>): Array<Attachment> => r.body);
  }

  /** Path part for operation `createAttachment()` */
  static readonly CreateAttachmentPath = '/api/orders/{orderId}/attachemets';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createAttachment()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createAttachment$Response(params: CreateAttachment$Params, context?: HttpContext): Promise<StrictHttpResponse<Attachment>> {
    const obs = createAttachment(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createAttachment$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createAttachment(params: CreateAttachment$Params, context?: HttpContext): Promise<Attachment> {
    const resp = this.createAttachment$Response(params, context);
    return resp.then((r: StrictHttpResponse<Attachment>): Attachment => r.body);
  }

  /** Path part for operation `getAttachmentById()` */
  static readonly GetAttachmentByIdPath = '/api/orders/{orderId}/attachemets/{attachemetsid}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAttachmentById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAttachmentById$Response(params: GetAttachmentById$Params, context?: HttpContext): Promise<StrictHttpResponse<Attachment>> {
    const obs = getAttachmentById(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAttachmentById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAttachmentById(params: GetAttachmentById$Params, context?: HttpContext): Promise<Attachment> {
    const resp = this.getAttachmentById$Response(params, context);
    return resp.then((r: StrictHttpResponse<Attachment>): Attachment => r.body);
  }

  /** Path part for operation `deleteAttachment()` */
  static readonly DeleteAttachmentPath = '/api/orders/{orderId}/attachemets/{attachemetsid}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteAttachment()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteAttachment$Response(params: DeleteAttachment$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = deleteAttachment(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteAttachment$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteAttachment(params: DeleteAttachment$Params, context?: HttpContext): Promise<void> {
    const resp = this.deleteAttachment$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

}
