/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createOrder } from '../fn/orders/create-order';
import { CreateOrder$Params } from '../fn/orders/create-order';
import { deleteOrder } from '../fn/orders/delete-order';
import { DeleteOrder$Params } from '../fn/orders/delete-order';
import { getAllOrders } from '../fn/orders/get-all-orders';
import { GetAllOrders$Params } from '../fn/orders/get-all-orders';
import { getOrderById } from '../fn/orders/get-order-by-id';
import { GetOrderById$Params } from '../fn/orders/get-order-by-id';
import { Order } from '../models/order';
import { updateOrder } from '../fn/orders/update-order';
import { UpdateOrder$Params } from '../fn/orders/update-order';

@Injectable({ providedIn: 'root' })
export class OrdersService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getOrderById()` */
  static readonly GetOrderByIdPath = '/api/orders/{orderId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getOrderById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getOrderById$Response(params: GetOrderById$Params, context?: HttpContext): Promise<StrictHttpResponse<Order>> {
    const obs = getOrderById(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getOrderById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getOrderById(params: GetOrderById$Params, context?: HttpContext): Promise<Order> {
    const resp = this.getOrderById$Response(params, context);
    return resp.then((r: StrictHttpResponse<Order>): Order => r.body);
  }

  /** Path part for operation `updateOrder()` */
  static readonly UpdateOrderPath = '/api/orders/{orderId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateOrder()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateOrder$Response(params: UpdateOrder$Params, context?: HttpContext): Promise<StrictHttpResponse<Order>> {
    const obs = updateOrder(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateOrder$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateOrder(params: UpdateOrder$Params, context?: HttpContext): Promise<Order> {
    const resp = this.updateOrder$Response(params, context);
    return resp.then((r: StrictHttpResponse<Order>): Order => r.body);
  }

  /** Path part for operation `deleteOrder()` */
  static readonly DeleteOrderPath = '/api/orders/{orderId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteOrder()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteOrder$Response(params: DeleteOrder$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = deleteOrder(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteOrder$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteOrder(params: DeleteOrder$Params, context?: HttpContext): Promise<void> {
    const resp = this.deleteOrder$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `getAllOrders()` */
  static readonly GetAllOrdersPath = '/api/orders';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllOrders()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllOrders$Response(params?: GetAllOrders$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<Order>>> {
    const obs = getAllOrders(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllOrders$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllOrders(params?: GetAllOrders$Params, context?: HttpContext): Promise<Array<Order>> {
    const resp = this.getAllOrders$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<Order>>): Array<Order> => r.body);
  }

  /** Path part for operation `createOrder()` */
  static readonly CreateOrderPath = '/api/orders';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createOrder()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createOrder$Response(params: CreateOrder$Params, context?: HttpContext): Promise<StrictHttpResponse<Order>> {
    const obs = createOrder(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createOrder$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createOrder(params: CreateOrder$Params, context?: HttpContext): Promise<Order> {
    const resp = this.createOrder$Response(params, context);
    return resp.then((r: StrictHttpResponse<Order>): Order => r.body);
  }

}
