/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createOrderLine } from '../fn/order-lines/create-order-line';
import { CreateOrderLine$Params } from '../fn/order-lines/create-order-line';
import { deleteOrderLine } from '../fn/order-lines/delete-order-line';
import { DeleteOrderLine$Params } from '../fn/order-lines/delete-order-line';
import { getAllOrderLines } from '../fn/order-lines/get-all-order-lines';
import { GetAllOrderLines$Params } from '../fn/order-lines/get-all-order-lines';
import { getOrderLineById } from '../fn/order-lines/get-order-line-by-id';
import { GetOrderLineById$Params } from '../fn/order-lines/get-order-line-by-id';
import { OrderLine } from '../models/order-line';

@Injectable({ providedIn: 'root' })
export class OrderLinesService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getAllOrderLines()` */
  static readonly GetAllOrderLinesPath = '/api/orders/{orderId}/lines';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllOrderLines()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllOrderLines$Response(params: GetAllOrderLines$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<OrderLine>>> {
    const obs = getAllOrderLines(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllOrderLines$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllOrderLines(params: GetAllOrderLines$Params, context?: HttpContext): Promise<Array<OrderLine>> {
    const resp = this.getAllOrderLines$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<OrderLine>>): Array<OrderLine> => r.body);
  }

  /** Path part for operation `createOrderLine()` */
  static readonly CreateOrderLinePath = '/api/orders/{orderId}/lines';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createOrderLine()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createOrderLine$Response(params: CreateOrderLine$Params, context?: HttpContext): Promise<StrictHttpResponse<OrderLine>> {
    const obs = createOrderLine(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createOrderLine$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createOrderLine(params: CreateOrderLine$Params, context?: HttpContext): Promise<OrderLine> {
    const resp = this.createOrderLine$Response(params, context);
    return resp.then((r: StrictHttpResponse<OrderLine>): OrderLine => r.body);
  }

  /** Path part for operation `getOrderLineById()` */
  static readonly GetOrderLineByIdPath = '/api/orders/{orderId}/lines/{lineId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getOrderLineById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getOrderLineById$Response(params: GetOrderLineById$Params, context?: HttpContext): Promise<StrictHttpResponse<OrderLine>> {
    const obs = getOrderLineById(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getOrderLineById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getOrderLineById(params: GetOrderLineById$Params, context?: HttpContext): Promise<OrderLine> {
    const resp = this.getOrderLineById$Response(params, context);
    return resp.then((r: StrictHttpResponse<OrderLine>): OrderLine => r.body);
  }

  /** Path part for operation `deleteOrderLine()` */
  static readonly DeleteOrderLinePath = '/api/orders/{orderId}/lines/{orderLineId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteOrderLine()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteOrderLine$Response(params: DeleteOrderLine$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = deleteOrderLine(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteOrderLine$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteOrderLine(params: DeleteOrderLine$Params, context?: HttpContext): Promise<void> {
    const resp = this.deleteOrderLine$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

}
