/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OrderLine } from '../../models/order-line';

export interface CreateOrderLine$Params {
  orderId: number;
      body: OrderLine
}

export function createOrderLine(http: HttpClient, rootUrl: string, params: CreateOrderLine$Params, context?: HttpContext): Observable<StrictHttpResponse<OrderLine>> {
  const rb = new RequestBuilder(rootUrl, createOrderLine.PATH, 'post');
  if (params) {
    rb.path('orderId', params.orderId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<OrderLine>;
    })
  );
}

createOrderLine.PATH = '/api/orders/{orderId}/lines';
