/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OrderLine } from '../../models/order-line';

export interface GetAllOrderLines$Params {
  orderId: number;
}

export function getAllOrderLines(http: HttpClient, rootUrl: string, params: GetAllOrderLines$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<OrderLine>>> {
  const rb = new RequestBuilder(rootUrl, getAllOrderLines.PATH, 'get');
  if (params) {
    rb.path('orderId', params.orderId, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<OrderLine>>;
    })
  );
}

getAllOrderLines.PATH = '/api/orders/{orderId}/lines';
